brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH
namesrvAddr = rocketmq-namesrv:9876
listenPort = 10911
autoCreateTopicEnable = true

# 向 namesrv 注册的对外地址，host 上的客户端通过 localhost:映射端口 连接
brokerIP1 = 127.0.0.1
