spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill_dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true

  data:
    redis:
      host: localhost

rocketmq:
  name-server: localhost:9876

jwt:
  secret: MzI4MjdhZjM2NTg5MGFmYjM2NTg5MGFmYjM2NTg5MGFmYjM2NTg5MA
  dev-auth-fallback: true

cors:
  allowed-origins: "*"

logging:
  level:
    com.seckill: debug
    com.baomidou.mybatisplus: debug
